### ISSUE TITLE
he images are down

### ISSUE THREAD

**Issue by Arclunar** [ZJU-FAST-Lab/uneven_planner#2]
Just a heads up: The images are down ( ´ ▽ ` )ﾉ

**Comment by Arclunar** [comment]
and some dependencies you miss in README:

sudo apt install ros-noetic-velocity-controllers 
sudo apt install ros-noetic-ompl 
sudo apt-get install ros-noetic-tf2-geometry-msgs ros-noetic-ackermann-msgs ros-noetic-joy ros-noetic-ma

**Comment by GaoLon** [comment]
> and some dependencies you miss in README:
> 
> sudo apt install ros-noetic-velocity-controllers sudo apt install ros-noetic-ompl sudo apt-get install ros-noetic-tf2-geometry-msgs ros-noetic-ackermann-msgs ros-noetic-joy ros-noetic-ma

Thanks♪(･ω･)ﾉ

**Comment by Arclunar** [comment]
您的邮件已收到，谢谢祝好!
